// Todo actions
export const TODOS_CREATE = 'TODOS_CREATE'
export const TODOS_TOGGLE_DONE = 'TODOS_TOGGLE_DONE'
export const TODOS_DELETE = 'TODOS_DELETE'

// Hotkey actions
export const HOTKEYS_MOVE_SELECTION_UP = 'HOTKEYS_MOVE_SELECTION_UP'
export const HOTKEYS_MOVE_SELECTION_DOWN = 'HOTKEYS_MOVE_SELECTION_DOWN'
export const HOTKEYS_REMOVE_SELECTION = 'HOTKEYS_REMOVE_SELECTION'